services:
  planeshift:
    container_name: planeshift
    image: ghcr.io/cclloyd/planeshift:latest
    ports:
      - "3000:3000"
    environment:
      SECRET_KEY: 'CHANGEME'
      MONGO_HOST: 'mongo'
      # MONGO_PORT: '27017'
      # MONGO_DB: 'planeshift'
      # MONGO_USER: 'planeshift'
      MONGO_PASS: 'CHANGEME'

      # Foundry settings
      FOUNDRY_HOST: 'https://dnd.example.com'
      # FOUNDRY_USER: 'APIUser'
      FOUNDRY_PASS: 'CHANGEME'
      # FOUNDRY_ADMIN_PASS: '' # Optional.  Gives additional control over restarting and managing the game.
      # FOUNDRY_LOG_ENABLED: 'false'

      # AUTH_PROVIDERS: 'discord,oidc' # csv list of providers to try sequentially.  If blank, authentication is disabled.

      # Discord auth settings
      # DISCORD_CLIENT_ID: 'CHANGEME'
      # DISCORD_CLIENT_SECRET: 'CHANGEME'
      # DISCORD_GUILD_ID: '' # (If omitted, anyone with a discord account can authenticate)
      # DISCORD_ROLE_ID: '' # (If omitted, anyone in the specified discord server can authenticate)
      # DISCORD_GM_ROLE_ID: '' # (If omitted, all users will be considered GMs)
      # DISCORD_ADMIN_ROLE_ID: '' (If omitted, all users will be considered admins in the API, bypassing all permission restrictions.)

      # OIDC Auth settings
      # OIDC_CLIENT_ID: ''
      # OIDC_CLIENT_SECRET: ''
      # OIDC_EXTRA_SCOPES: ''
      # OIDC_USERNAME_ATTRIBUTE: ''
      # OIDC_ROLE_CLAIM: ''
      # OIDC_GM_ROLE: ''
      # OIDC_ADMIN_ROLE: ''

#  mongo:
#    container_name: mongo
#    image: mongo
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongo-data:/data/db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: 'planeshift'
#      MONGO_INITDB_ROOT_PASSWORD: 'CHANGEME'

#volumes:
#  mongo-data:
